### ISSUE TITLE
Volumes are created as Thick Provisioned by default

### ISSUE THREAD

**Issue by raul-pingarron** [NetApp/netapp-data-science-toolkit#1]
Volumes are created as Thick Provisioned by default, this is per ONTAP's API [here](https://library.netapp.com/ecmdocs/ECMLP2858435/html/resources/volume.html) (`guarantee.type=volume` if nothing is specified)
There is no way to specify that a volume should be created as **Thin Provisioned** (`guarantee.type=none`), which I think it makes more sense for the shake of the system's efficiency.

I'm attaching a version containing an enhancement to create the volumes as Thin Provisioned by default, unless otherwise specified by adding the option <`guarantee="volume"`> to the `createVolume()` method, or by passing "`-r volume`" or "`--space-guarantee=volume`" in the cmdline.

[ntap_dsutil.txt](https://github.com/NetApp/netapp-data-science-toolkit/files/5822539/ntap_dsutil.txt)

**Comment by mboglesby** [comment]
Thanks for catching this, Raul! I will enhance the tool as you suggested. Expect this enhancement to be included in v1.1 which is scheduled for release at the end of this month (January 2021).

**Comment by mboglesby** [comment]
This has been fixed.
