### ISSUE TITLE
Question about Sample Code (AttributeError: The 'nas' field has not been set on the Volume)

### ISSUE THREAD

**Issue by sakaia** [NetApp/netapp-data-science-toolkit#2]
I try to execute [Sample Code](https://github.com/NetApp/netapp-data-science-toolkit/blob/main/Examples.ipynb). It almost works successfully but some command does not work properly.
The error message is follows.

```
>>> createVolume(volumeName="test2", volumeSize="20MB", mountpoint="~/test2", printOutput=True)
Creating volume 'test2'.
Volume created successfully.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sakaia/netapp-data-science-toolkit/ntap_dsutil.py", line 519, in createVolume
    mountVolume(volumeName=volumeName, mountpoint=mountpoint, printOutput=True)
  File "/home/sakaia/netapp-data-science-toolkit/ntap_dsutil.py", line 350, in mountVolume
    volumes = listVolumes(checkLocalMounts=True)
  File "/home/sakaia/netapp-data-science-toolkit/ntap_dsutil.py", line 263, in listVolumes
    if volume.nas.path != "/" :
  File "/usr/local/lib/python3.6/dist-packages/netapp_ontap/resource.py", line 278, in __getattribute__
    ) from None
AttributeError: The 'nas' field has not been set on the Volume. Try refreshing the object by calling get().
```

Would you give me any suggestion? 
it seems relates to local mount setting. But manual operation `mount 172.16.28.135:/test1 /mnt` works fine. So NFS export problem seems not exist.
Also I read through [troubleshooting.md](https://github.com/NetApp/netapp-data-science-toolkit/blob/main/troubleshooting.md), it describes NFS export problem only.

-  `createVolume` Example 2
-  `listVolume` Example 3, 4, 5

```
$ cat ~/.ntap_dsutil/config.json
{"connectionType": "ONTAP", "hostname": "172.16.28.131", "svm": "svm0", "dataLif": "172.16.28.135", "defaultVolumeType": "flexgroup", "defaultExportPolicy": "default", "defaultSnapshotPolicy": "none", "defaultUnixUID": "0", "defaultUnixGID": "0", "defaultUnixPermissions": "0777", "defaultAggregate": "ontapsim_01_FC_1", "username": "admin", "password": "b250YXBzaW0w", "verifySSLCert": false}
```

**Comment by sakaia** [comment]
@raul-pingarron Thanks for your help. it almost works for me. One example still remain.
  
Is example 12 really working? because  snap1 of  test2 deleted already. the snapshot state is not required for `sourceSnapshotName`
I am doing work around for create snap1 again then works fine.

**Comment by raul-pingarron** [comment]
> @raul-pingarron Thanks for your help. it almost works for me. One example still remain.
> 
> Is example 12 really working? because snap1 of test2 deleted already. the snapshot state is not required for `sourceSnapshotName`
> I am doing work around for create snap1 again then works fine.

Indeed example 12 shouldn't work if cell 13 (Example 9) has been previosuly executed; but this is just a Jupyter Notebook example and you should modify it accordingly (i.e. you could use the "ntap_dsutil_20201113_221917" snapshot instead).

**Comment by sakaia** [comment]
Thanks!

All problem solved.
